version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  flight:
    image: flight
    build: ./flight/
    ports:
      - "8060:8060"
      
  ticket:
    image: ticket
    build: ./ticket/
    ports:
      - "8070:8070"
      
  bonus:
    image: bonus
    build: ./bonus/
    ports:
      - "8050:8050"

  gateway:
    image: gateway
    build: ./gateway/
    ports:
      - "8080:8080"
    
volumes:
  db-data: